package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// mockWrapper is one script to write: the file name a build tool invokes, and
// the leaf path that answers for it.
type mockWrapper struct {
	name string
	path []string
}

// collectMockWrappers walks the tree for every <mock> leaf. The script takes
// the leaf's own name, because that is the name the build calls: a leaf at
// "tools cc" installs as "cc".
func collectMockWrappers(cmds []Command, path []string) []mockWrapper {
	var out []mockWrapper
	for _, c := range cmds {
		here := append(append([]string{}, path...), c.Name)
		if c.Mock != nil {
			out = append(out, mockWrapper{name: c.Name, path: here})
		}
		out = append(out, collectMockWrappers(c.Commands, here)...)
	}
	return out
}

// installMockWrappers writes one executable script per <mock> leaf into dir.
// Putting that directory first on PATH is the whole installation: a build then
// reaches the stand-in instead of the real tool, and nothing in the build
// system itself changes.
func installMockWrappers(cfg *Config, configPath, dir string, out io.Writer) error {
	if cfg == nil {
		return fmt.Errorf("--install-mocks needs a config")
	}

	wrappers := collectMockWrappers(cfg.Commands, nil)
	if len(wrappers) == 0 {
		return fmt.Errorf("%s declares no <mock> leaf, so there is nothing to install", configPath)
	}

	// Two leaves of one name install one script, and the second silently wins.
	// A build that then calls the wrong stand-in is very hard to read back.
	seen := map[string][]string{}
	for _, w := range wrappers {
		if prev, dup := seen[w.name]; dup {
			return fmt.Errorf("two mock leaves are both named %q (%s and %s); one script cannot answer for both",
				w.name, strings.Join(prev, " "), strings.Join(w.path, " "))
		}
		seen[w.name] = w.path
	}

	self, err := os.Executable()
	if err != nil {
		return fmt.Errorf("--install-mocks: locate this binary: %w", err)
	}
	// A wrapper outlives the shell that wrote it, and a build tool runs it from
	// whatever directory it likes. Both paths are therefore absolute.
	absConfig, err := filepath.Abs(configPath)
	if err != nil {
		return fmt.Errorf("--install-mocks: %s: %w", configPath, err)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("--install-mocks: %s: %w", dir, err)
	}

	for _, w := range wrappers {
		script := filepath.Join(dir, w.name)
		body := wrapperScript(self, absConfig, w.path)
		if err := os.WriteFile(script, []byte(body), 0o755); err != nil {
			return fmt.Errorf("--install-mocks: %s: %w", script, err)
		}
		// WriteFile leaves an existing file's mode alone, and a wrapper that is
		// not executable fails the build with "permission denied".
		if err := os.Chmod(script, 0o755); err != nil {
			return fmt.Errorf("--install-mocks: %s: %w", script, err)
		}
		fmt.Fprintf(out, "%s -> %s\n", script, strings.Join(w.path, " "))
	}

	fmt.Fprintf(out, "\nPut it first on PATH:\n    export PATH=%q:$PATH\n", mustAbs(dir))
	return nil
}

// wrapperScript is the script a build tool executes. The "--" is what makes
// the leaf's passthrough mode see the real argv rather than this tool's flags.
func wrapperScript(self, config string, path []string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by api-cli --install-mocks. Edit the config, not this file.\n")
	b.WriteString("exec ")
	b.WriteString(shellQuote(self))
	b.WriteString(" --config ")
	b.WriteString(shellQuote(config))
	for _, seg := range path {
		b.WriteString(" ")
		b.WriteString(shellQuote(seg))
	}
	b.WriteString(` -- "$@"` + "\n")
	return b.String()
}

func mustAbs(dir string) string {
	abs, err := filepath.Abs(dir)
	if err != nil {
		return dir
	}
	return abs
}
